
platform :ios, '8.0'

source 'https://github.com/CocoaPods/Specs.git'

#use_frameworks!

target 'JoyKit_Example' do
  pod 'SDWebImage'
  pod 'MJExtension'
  pod 'JoyKit', :path => '../'
  target 'JoyKit_Tests' do
    inherit! :search_paths
  end
end
